name: setup rye
description: GitHub Action for setup mitsuhiko/rye
author: '@sksat'
branding:
  icon: activity
  color: green

inputs:
  version:
    required: true
    description: rye version
    # renovate: depName=astral-sh/rye datasource=github-releases
    default: '0.38.0'
  use-uv:
    required: false
    description: behavior use use
    default: 'false'

runs:
  using: "composite"
  steps:
  - name: install rye
    shell: bash
    env:
      RYE_INSTALL_OPTION: '--yes'
      RYE_VERSION: ${{ inputs.version }}
    run: |
      curl -sSf https://rye.astral.sh/get | bash

  - name: setup rye path
    shell: bash
    run: |
      echo "$HOME/.rye/shims" >> $GITHUB_PATH

  - name: setup uv behavior
    shell: bash
    if: ${{ inputs.use-uv == 'true' }}
    run: rye config --set-bool behavior.use-uv=true
