name: reviewdog / actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: actionlint
        uses: reviewdog/action-actionlint@af17f9e3640ac863dbcc515d45f5f35d708d0faf # v1.62.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
