name: reviewdog / actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: actionlint
        uses: reviewdog/action-actionlint@af17f9e3640ac863dbcc515d45f5f35d708d0faf # v1.62.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
