name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
        use-uv:
          - true
          - false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ./
        with:
          use-uv: ${{ matrix.use-uv }}

      - run: rye --version
