name: validate renovate

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'renovate.json5'
      - '.github/workflows/validate-renovate.yml'

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator
